import Link from 'next/link';

export default function Hero() {
  return (
    <section className='relative bg-[#151522]'>
      <svg
        className='absolute w-full'
        fill='none'
        viewBox='0 0 960 637'
        height='100%'
        width='100%'
        xmlns='http://www.w3.org/2000/svg'
      >
        <g filter='url(#filter0_f_1_167)'>
          <ellipse
            cx='479.5'
            cy='318.5'
            fill='#687af0'
            fill-opacity='0.5'
            rx='118.5'
            ry='118.5'
            transform='rotate(-90 479.5 318.5)'
          ></ellipse>
        </g>
        <mask
          height='573'
          id='mask0_1_167'
          maskUnits='userSpaceOnUse'
          width='960'
          x='0'
          y='32'
        >
          <rect
            height='573'
            width='960'
            y='32'
            fill='url(#paint0_radial_1_167)'
          ></rect>
        </mask>
        <g mask='url(#mask0_1_167)'>
          <rect height='79' width='79' y='41.5' stroke='white' x='123.5'></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='202.5'></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='281.5'></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='360.5'></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='439.5'></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='518.5'></rect>
          <rect
            height='79'
            width='79'
            y='41.5'
            stroke='white'
            x='597.5'
            fill='white'
            fill-opacity='0.25'
          ></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='676.5'></rect>
          <rect height='79' width='79' y='41.5' stroke='white' x='755.5'></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='123.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='202.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='281.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='360.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='439.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='518.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='597.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='676.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='120.5'
            stroke='white'
            x='755.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='123.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='202.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='281.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='360.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='439.5'
            fill='white'
            fill-opacity='0.25'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='518.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='597.5'
            fill='white'
            fill-opacity='0.25'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='676.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='199.5'
            stroke='white'
            x='755.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='123.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='202.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='281.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='360.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='439.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='518.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='597.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='676.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='278.5'
            stroke='white'
            x='755.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='123.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='202.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='281.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='360.5'
            fill='white'
            fill-opacity='0.25'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='439.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='518.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='597.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='676.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='357.5'
            stroke='white'
            x='755.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='123.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='202.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='281.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='360.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='439.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='518.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='597.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='676.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='436.5'
            stroke='white'
            x='755.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='123.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='202.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='281.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='360.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='439.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='518.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='597.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='676.5'
          ></rect>
          <rect
            height='79'
            width='79'
            y='515.5'
            stroke='white'
            x='755.5'
          ></rect>
        </g>
        <defs>
          <filter
            color-interpolation-filters='sRGB'
            filterUnits='userSpaceOnUse'
            height='637'
            id='filter0_f_1_167'
            width='637'
            x='161'
            y='1.14441e-05'
          >
            <feFlood flood-opacity='0' result='BackgroundImageFix'></feFlood>
            <feBlend
              in='SourceGraphic'
              in2='BackgroundImageFix'
              mode='normal'
              result='shape'
            ></feBlend>
            <feGaussianBlur
              result='effect1_foregroundBlur_1_167'
              stdDeviation='100'
            ></feGaussianBlur>
          </filter>
          <radialGradient
            cx='0'
            cy='0'
            gradientTransform='translate(480 318.5) rotate(90) scale(353.19 591.732)'
            gradientUnits='userSpaceOnUse'
            id='paint0_radial_1_167'
            r='1'
          >
            <stop stop-color='#D9D9D9' stop-opacity='0.2'></stop>
            <stop
              stop-color='#D9D9D9'
              stop-opacity='0'
              offset='0.802083'
            ></stop>
          </radialGradient>
        </defs>
      </svg>
      <div className='relative mx-auto w-full max-w-7xl items-center px-5 py-12 md:px-12 lg:px-16 lg:py-12'>
        <div className='mx-auto text-center'>
          <div>
            <p className='text-4xl font-medium tracking-tight text-white md:text-7xl'>
              1:1 coworking space
              <span className='md:block'>for remote workers</span>
            </p>
            <p className='mx-auto mt-8 max-w-xl text-base text-white/70 lg:text-xl'>
              Monoqrom is a Figma community file that helps you design and
              prototype a 1:1 coworking space for remote workers.
            </p>
          </div>
          <div className='mt-10 flex flex-col justify-center gap-3 sm:flex-row'>
            <a
              className='inline-flex w-full items-center justify-center rounded-xl bg-[#687af0]/5 px-6 py-3 text-center font-medium text-white duration-200 hover:bg-[#687af0]/5 hover:text-[#687af0] focus:outline-none focus-visible:outline-black focus-visible:ring-black lg:w-auto'
              href='#'
            >
              Learn More →
            </a>
            <Link
              className='inline-flex w-full items-center justify-center rounded-xl bg-gradient-to-b from-indigo-300 via-indigo-400 to-indigo-500 px-6 py-3 text-center font-medium text-white transition-all duration-200 hover:bg-[#687af0]/5 hover:to-indigo-600 hover:text-[#fff] focus:outline-none focus-visible:outline-black focus-visible:ring-black lg:w-auto'
              href='/sign-in'
            >
              Start Now
            </Link>
          </div>
        </div>
        <div className='relative mx-auto mt-12 w-full max-w-7xl items-center pb-12'>
          <div>
            <video
              className='w-full rounded object-cover lg:rounded-2xl'
              height='100%'
              width='100%'
              autoPlay
              muted
              loop
            >
              <source
                src='https://d33wubrfki0l68.cloudfront.net/b3fb0d3c87038c6a1517d3220eedee8bead88964/419d0/monoqrom.mp4'
                type='video/mp4'
              />
              Your browser does not support the video tag.
            </video>
          </div>
        </div>
      </div>
    </section>
  );
}
